{% set name = "sqltoast" %} 
{% set version = "1.0.0" %} 
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/cill-airne/sqltoast.git
  git_depth: 1 # (Defaults to -1/not shallow)

build:
  number: 1

requirements:
  build:
    - cmake
    - make  # [unix]
    - libunwind
    - {{ compiler('cxx') }}

about:
  summary: 'SQL'
  description: 'SQL'
